#define _GNU_SOURCE 1
#include "stmgc.h"
#include "stm/atomic.h"
#include "stm/list.h"
#include "stm/core.h"
#include "stm/nursery.h"
#include "stm/sync.h"
#include "stm/setup.h"
#include "stm/fprintcolor.h"
#include "stm/rewind_setjmp.h"

#include "stm/list.c"
#include "stm/nursery.c"
#include "stm/core.c"
#include "stm/sync.c"
#include "stm/setup.c"
#include "stm/fprintcolor.c"
#include "stm/rewind_setjmp.c"
#include "stm/misc.c"
