#!/bin/sh

export C2LSL_HOME=./c2lsl
export CHECKFENCE_HOME=./checkfence


$C2LSL_HOME/bin/c2lsl.exe "$1" _run.lsl || exit 1
shift
$CHECKFENCE_HOME/run/clean || exit 1
echo -------------------------------------------------------------------------
$CHECKFENCE_HOME/run/checkfence -i _run.lsl "$@" || exit 1
